<?php
if (!is_file('/.dockerenv')) { throw new RuntimeException('Use a disposable test container.'); }
$base=__DIR__.'/../../source/usr/local/emhttp/plugins/zfs.snapsync/php';
require $base.'/coordinator-state.php';
require $base.'/replication-plan.php';
require $base.'/snapshot-manager-helpers.php';
function check($ok,$why){if(!$ok)throw new RuntimeException($why);}
function reject($fn){try{$fn();}catch(InvalidArgumentException $error){return;}throw new RuntimeException('Invalid endpoint authority accepted');}
$key='SHA256:'.str_repeat('A',43);
$a=ZfsasEndpointIdentity::receiver($key,'10');$b=ZfsasEndpointIdentity::receiver($key,'20');
check($a!==$b,'Distinct receiver pools share identity');
check($a===ZfsasEndpointIdentity::receiver($key,'10'),'Host alias changed storage identity');
check(ZfsasEndpointIdentity::receiver($key,'10',['10'])==='local','SSH alias bypassed local ownership');
reject(fn()=>ZfsasEndpointIdentity::receiver('unverified','10'));
reject(fn()=>ZfsasEndpointIdentity::validate('ssh:hostname'));
check(ZfsasEndpointIdentity::mayOverlap('old-host-label',$a),'Legacy identity weakened exclusion');
$j=new ZfsasCoordinatorState('/tmp/endpoint-test-'.bin2hex(random_bytes(6)));
$ref=['role'=>'base','endpoint'=>$a,'dataset'=>'tank/data','datasetGuid'=>'42','snapshot'=>'tank/data@base','guid'=>'123'];
$owner=$j->submit('remote-reference',['tasks'=>['send'=>['kind'=>'send','references'=>[$ref]]]],1)['runId'];
check($j->deletionReferenceOwners('tank/data@base','123',$a)===[$owner],'Receiver protection missing');
check(!$j->deletionReferenceOwners('tank/data@base','123',$b),'Different host/pool snapshot was blocked');
check(!$j->deletionReferenceOwners('tank/data@base','123','local'),'Remote name collided with local snapshot');
check($j->deletionReferenceOwners('tank/data@base','123')===[$owner],'Unscoped legacy protection disappeared');
$task=['kind'=>'delete','parameters'=>['endpoint'=>$b,'deleteJob'=>['SNAPSHOT'=>'tank/data@base','SNAPSHOT_GUID'=>'123']]];
$delete=$j->submit('other-endpoint',['tasks'=>['delete'=>$task]],1)['runId'].':delete';$j->claim($delete,1,1);
$j->submit('same-name-other-host',['tasks'=>['send'=>['kind'=>'send','references'=>[$ref]]]],1);
$otherRef=array_replace($ref,['endpoint'=>$b]);
reject(fn()=>$j->submit('racing-delete',['tasks'=>['send'=>['kind'=>'send','references'=>[$otherRef]]]],1));
$own=$j->submit('own-plan',['tasks'=>['source'=>['kind'=>'prepare','references'=>[$ref]],'delete'=>$task]],1);
check(isset($own['runId']),'Remote reference incorrectly rejected different-pool cleanup');
reject(fn()=>$j->submit('self-delete',['tasks'=>['source'=>['kind'=>'prepare','references'=>[$ref]],'delete'=>array_replace_recursive($task,['parameters'=>['endpoint'=>$a]])]],1));
$locks=zfsas_ops_dataset_gates('tank/data',$a);check(is_array($locks),'Remote gate failed');
check(zfsas_ops_dataset_gates('tank/data/child',$a)===false,'Ancestor lock bypassed');
$other=zfsas_ops_dataset_gates('tank/data',$b);check(is_array($other),'Different endpoint cannot run independently');
$local=zfsas_ops_dataset_gates('tank/data');check(is_array($local),'Local names collided with remote locks');
$blocked=zfsas_ops_resource_gates([['endpoint'=>$b,'dataset'=>'other/data'],['endpoint'=>$a,'dataset'=>'tank/data']]);
check($blocked===false,'Partially available resources admitted');
$released=zfsas_ops_dataset_gates('other/data',$b);check(is_array($released),'Failed admission retained locks');
foreach(array_merge($locks,$other,$local,$released) as $handle)fclose($handle);

$request=['sourceSnapshot'=>'tank/source@new','sourceGuid'=>'300','destination'=>'backup/target'];
$source=function($args){$name=end($args);check(str_starts_with($name,'tank/source')||$args[0]==='send','Receiver command executed on source');
 if($args[0]==='send')return "size\t100\n";
 if($args[0]==='list')return "tank/source@base\t200\t1\ntank/source@new\t300\t2\n";
 return match($name){'tank/source'=>'10','tank/source@new'=>'300','tank/source@base'=>'200'};};
$receiver=function($args){$name=end($args);check(str_starts_with($name,'backup/target'),'Source command executed on receiver');
 if(in_array('available',$args,true))return '100000000';
 if(in_array('receive_resume_token',$args,true))return '-';
 if($args[0]==='list')return "backup/target@base\t200\t1\n";
 return $name==='backup/target'?'20':'200';};
$result=ZfsasReplicationInspection::inspect($request,$source,$receiver,$a);
check($result['inspection']['receiverEndpoint']===$a,'Inspection lost receiver identity');
check(array_column($result['inspection']['references'],'endpoint')===['local','local',$a],'References went to the wrong endpoint');
$plan=zfsas_replication_plan($request,$result['inspection'],str_repeat('a',64));
check($plan['tasks']['space']['parameters']['endpoint']===$a,'Plan lost receiver identity');
check(zfsas_replication_space($plan['tasks']['space']['parameters'],$source,null,$receiver)['outcome']==='success','Space preflight did not separate endpoints');
reject(fn()=>zfsas_replication_revalidate($plan['tasks']['space']['parameters'],$source,$receiver,$b));
$decode=function($args)use($source){return in_array('-nvt',$args,true)?"toname = tank/source@new\ntoguid = 300\nfromguid = 200\n":$source($args);};
$resumeReceiver=function($args)use($receiver){return in_array('receive_resume_token',$args,true)?'private-token':$receiver($args);};
$resumed=ZfsasReplicationInspection::inspect($request+['allowResume'=>true],$decode,$resumeReceiver,$a);
check($resumed['inspection']['mode']==='resume','Resume inspection failed');
check(!str_contains(json_encode($resumed),'private-token'),'Resume plan exposed raw token');
check(array_column($resumed['inspection']['references'],'endpoint')===['local','local',$a],'Resume base lost its receiver scope');
$resumePlan=zfsas_replication_plan($request+['allowResume'=>true],$resumed['inspection'],str_repeat('a',64));
check(zfsas_replication_space($resumePlan['tasks']['space']['parameters'],$decode,null,$resumeReceiver)['outcome']==='success','Resume token was read on source');
$newReceiver=function($args){check(end($args)==='backup','New receiver inspected the wrong parent');return $args[0]==='list'?'backup':'900';};
$new=ZfsasReplicationInspection::inspect($request+['createDestination'=>true,'destinationParentGuid'=>'900'],$source,$newReceiver,$a);
check($new['inspection']['mode']==='full' && $new['inspection']['receiverEndpoint']===$a,'New target lost receiver identity');
echo "PASS: endpoint identities, aliases, local/remote isolation, legacy exclusions, atomic resource locks and separate source/receiver reads\n";
