const {chromium}=require('/opt/zfsas-tests/node_modules/playwright-core');
const {execFileSync}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const plugin=path.resolve(__dirname,'../../source/usr/local/emhttp/plugins/zfs.snapsync');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],posts=[];let fail=false;
page.on('pageerror',e=>errors.push(e.message));
await page.route('http://guided.test/**',async route=>{const url=new URL(route.request().url());
if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:execFileSync('php',['-r','parse_str($argv[1],$_GET);require $argv[2];',url.search.slice(1),plugin+'/php/workspace.php'],{encoding:'utf8'})});
if(/\.(js|css|png)$/.test(url.pathname))return route.fulfill({contentType:url.pathname.endsWith('.js')?'application/javascript':url.pathname.endsWith('.css')?'text/css':'image/png',body:fs.readFileSync(plugin+url.pathname.replace('/plugins/zfs.snapsync',''))});
let data={ok:true,probe:true,spec:{kind:'interval',seconds:21600},nextScheduledText:'Tomorrow',available:true,status:{},runs:[],datasets:[{dataset:'tank/photos',pool:'tank',sendDestination:false},{dataset:'tank/documents',pool:'tank',sendDestination:false}],sources:{},operations:[],schedules:[],pausedSchedules:[]};
if(route.request().method()==='POST'&&!new URLSearchParams(route.request().postData()).has('probe')&&/save-(send-)?settings.php$/.test(url.pathname)){const post=new URLSearchParams(route.request().postData());posts.push(post);data=fail?{ok:false,saved:false,errors:['Settings changed. Draft retained.']}:{ok:true,saved:true,schedulerApplied:false,revision:'saved-revision',jobs:[],notices:['Scheduler application failed.']};}
return route.fulfill({contentType:'text/plain',body:'ZFSAS_JSON_BEGIN'+JSON.stringify(data)+'ZFSAS_JSON_END'});
});
async function fits(id){const b=await page.locator(id).boundingBox();if(b&&b.y+b.height>768)await page.screenshot({path:'/tmp/zfsas-ui-screenshots/step-overflow.png',fullPage:true});assert(b&&b.y+b.height<=768,'Primary action below laptop viewport: '+JSON.stringify(b));}
await page.goto('http://guided.test/?section=automation');await page.getByRole('button',{name:'Set up automatic snapshots'}).click();await page.waitForFunction(()=>document.querySelectorAll('.zfsas-dataset-checkbox').length===2);await page.locator('#dataset-page-checkbox').check();await fits('.zfsas-actions .btn-primary:visible');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.selectOption('#schedule_mode','daily');await fits('.zfsas-actions .btn-primary:visible');await page.getByRole('button',{name:'Continue',exact:true}).click();await fits('#zfsas_save_btn');fail=true;await page.locator('#zfsas_save_btn').click();await page.waitForFunction(()=>document.getElementById('save_feedback').textContent.includes('Draft retained'));assert.equal(await page.locator('#schedule_mode').inputValue(),'daily');fail=false;await page.locator('#zfsas_save_btn').click();await page.waitForFunction(()=>!document.getElementById('automation-summary').hidden);assert.match(await page.locator('#workspace-notice').textContent(),/Settings saved/);await page.locator('#automation-summary button').nth(1).click();await page.selectOption('#schedule_mode','weekly');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('#schedule_mode').inputValue(),'daily');assert.equal(await page.locator('#zfsas_settings_form').getAttribute('data-dirty'),'false');
await page.goto('http://guided.test/?section=replication');await page.locator('#open-new-job').click();await page.waitForFunction(()=>document.querySelector('#job-editor-body [name^="job_source["]').options.length>1);await page.locator('#job-editor-body [name^="job_source["]').selectOption('tank/photos');await page.locator('#job-editor-body [name^="job_destination["]').fill('backup/photos');await page.locator('#job-editor-body [name^="job_transport["]').selectOption('ssh');await page.getByRole('button',{name:'Set up connection'}).click();await page.locator('#send_ssh_host').fill('backup.local');await page.locator('#save_send_btn').click();await page.waitForFunction(()=>!document.getElementById('edit-job-dialog').hidden);assert.equal(await page.locator('#job-editor-body [name^="job_destination["]').inputValue(),'backup/photos');assert.equal(posts.at(-1).get('scope'),'shared');assert.equal(posts.at(-1).get('job_source[0]'),null);await fits('#finish-job-edit');await page.locator('#finish-job-edit').click();await fits('#finish-job-edit');await page.locator('#finish-job-edit').click();await fits('#finish-job-edit');
fs.mkdirSync('/tmp/zfsas-ui-screenshots',{recursive:true});await page.screenshot({path:'/tmp/zfsas-ui-screenshots/guided-review-laptop.png'});
assert.deepEqual(errors,[]);console.log('PASS: laptop step bounds, failed saves preserve drafts, saved/runtime distinction, cancel restoration, SSH shared save returns to isolated job draft');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
