/* Static design preview: fixtures only, no plugin endpoint requests allowed. */
const {chromium}=require('/opt/zfsas-tests/node_modules/playwright-core');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),out='/tmp/zfsas-design-preview';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
await page.route('http://preview.test/**',route=>{const pathname=new URL(route.request().url()).pathname;requests.push(pathname);const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+'/docs/preview/')&&!file.endsWith('/images/zfs-snapsync.png'))throw Error('Unexpected preview request: '+pathname);return route.fulfill({contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html',body:fs.readFileSync(file)});});
await page.goto('http://preview.test/docs/preview/index.html');
async function nav(name){await page.locator('#navigation a[data-page="'+name+'"]').click();}
async function shot(name){await page.evaluate(()=>document.getElementById('toast').hidden=true);await page.screenshot({path:out+'/'+name+'.png',fullPage:true});}
async function fits(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow');}
async function stepFits(){const box=await page.locator('#flow-next').boundingBox();assert(box.y+box.height<=768,'Setup primary action requires scrolling: '+JSON.stringify(box));}
await shot('overview-light');await nav('backups');await page.locator('[data-action="edit-job"]').first().click();assert(await page.getByRole('heading',{name:'Backup: photos'}).isVisible());await page.locator('[data-action="job-edit-schedule"]').click();await page.selectOption('[name=schedule]','7d');await page.selectOption('[name=day]','2');await page.locator('#flow-next').click();await page.getByRole('heading',{name:'Backup: photos'}).waitFor();assert.match(await page.locator('.summary-panel').textContent(),/Tuesday/);
await page.selectOption('#scenario','empty');await nav('overview');await shot('first-visit');await page.locator('[data-action="start-auto"]').first().click();await stepFits();await page.locator('[data-dataset="tank/photos"]').check();await page.locator('[data-dataset="tank/documents"]').check();await page.fill('#dataset-filter','photos');assert.equal(await page.locator('#dataset-count').textContent(),'2 selected');await page.fill('#dataset-filter','');await shot('setup-data');await page.locator('#flow-next').click();await stepFits();await page.selectOption('[name=schedule]','1d');await page.fill('[name=time]','03:30');await shot('setup-schedule');await page.locator('#flow-next').click();await stepFits();await shot('setup-review');await page.locator('#flow-next').click();await page.locator('[data-action="edit-auto-data"]').waitFor();assert.match(await page.locator('.summary-panel').textContent(),/03:30/);
await page.locator('[data-action="edit-auto-schedule"]').click();await page.selectOption('[name=schedule]','12h');await nav('overview');await page.getByRole('heading',{name:'Leave without saving?'}).waitFor();await page.locator('[data-action="close-dialog"]').last().click();assert.equal(await page.locator('[name=schedule]').inputValue(),'12h');await page.locator('[data-action="cancel-flow"]').click();await page.locator('[data-action="discard-flow"]').click();
await nav('backups');await page.locator('[data-action="start-job"]').first().click();await page.selectOption('[name=transport]','ssh');await page.fill('[name=destination]','remote/photos');await page.locator('[data-action="connection-setup"]').click();await page.fill('[name=host]','backup.local');await page.locator('#flow-next').click();await page.waitForFunction(()=>document.querySelector('[name=destination]'));assert.equal(await page.locator('[name=destination]').inputValue(),'remote/photos');assert.match(await page.locator('.connection-summary').textContent(),/backup.local/);await page.locator('#flow-next').click();await stepFits();await page.locator('#flow-next').click();await stepFits();await page.locator('#flow-next').click();await page.getByRole('heading',{name:'Backup copies',exact:true}).waitFor();
await page.selectOption('#scenario','configured');await nav('backups');await page.locator('[data-action="start-job"]').click();await page.fill('[name=destination]','backup/photos-new');await page.locator('#flow-next').click();await page.locator('#flow-next').click();await page.locator('#flow-next').click();assert.match(await page.locator('#flow-error').textContent(),/Review the existing/);await page.locator('[data-action="source-review"]').click();await page.locator('[data-action="accept-source-review"]').click();await shot('source-review-approved');await page.locator('#flow-next').click();await page.getByRole('heading',{name:'Backup copies',exact:true}).waitFor();
await page.selectOption('#scenario','save-error');await nav('automation');await page.locator('[data-action="edit-auto-schedule"]').click();await page.selectOption('[name=schedule]','12h');await page.locator('#flow-next').click();await page.waitForFunction(()=>document.querySelector('#flow-error')?.textContent.includes('Settings changed'));await shot('save-error');assert.equal(await page.locator('[name=schedule]').inputValue(),'12h');await page.locator('#flow-next').click();await page.locator('[data-action="edit-auto-schedule"]').waitFor();
await nav('snapshots');await fits();let fifth=await page.locator('tbody tr').nth(4).boundingBox();assert(fifth.y+fifth.height<=768,'Fewer than five snapshot rows visible');await page.locator('#page-selection').check();assert.match(await page.locator('.selection-bar strong').textContent(),/19 selected/);await page.locator('[data-action="select-matching"]').click();assert.match(await page.locator('.selection-bar strong').textContent(),/239 selected/);await shot('snapshots-selected');assert((await page.locator('.pager').boundingBox()).y<768,'Pagination left the laptop viewport');await page.locator('[data-action="bulk-delete"]').click();assert.match(await page.locator('#dialog-body').textContent(),/excluded/);await shot('delete-review');await page.keyboard.press('Escape');await page.locator('[data-action="clear-selection"]').click();await page.locator('tbody .action-menu summary').first().click();await page.locator('[data-action="snapshot-restore"]').first().click();assert.match(await page.locator('#dialog-body').textContent(),/new writable dataset/);await shot('restore-dialog');await page.keyboard.press('Escape');assert(await page.locator('tbody .action-menu summary').first().evaluate(el=>el===document.activeElement));
await page.selectOption('#scenario','error');await nav('activity');await page.locator('[data-action="operation-details"]').first().click();await page.locator('[data-action="operation-tab"][data-value="steps"]').click();assert.equal(await page.locator('.checklist li').count(),6);await page.locator('[data-action="operation-tab"][data-value="logs"]').click();await page.selectOption('#log-scope','shared');assert.match(await page.locator('#log-scope-note').textContent(),/other jobs/);await shot('activity-logs');await page.keyboard.press('Escape');
await nav('settings');await page.locator('[data-action="start-migration"]').click();await page.locator('#flow-next').click();await page.locator('#flow-next').click();await page.locator('#flow-next').click();assert.match(await page.locator('#flow-error').textContent(),/Acknowledge/);await page.locator('[name=acknowledged]').check();await page.locator('#flow-next').click();await page.getByRole('heading',{name:'Migration started'}).waitFor();
for(const theme of ['light','dark']){if(theme==='dark')await page.locator('#theme-toggle').click();await page.selectOption('#scenario','configured');for(const view of ['overview','automation','snapshots','backups','activity','settings','help']){await nav(view);await shot(view+'-'+theme);await fits();}await page.setViewportSize({width:390,height:844});for(const view of ['overview','automation','snapshots','backups','activity','settings','help']){await page.locator('#nav-toggle').click();await nav(view);await fits();await shot(view+'-'+theme+'-mobile');}await page.locator('#nav-toggle').click();await nav('backups');await page.locator('[data-action="start-job"]').click();await fits();await shot('job-setup-'+theme+'-mobile');await page.locator('[data-action="cancel-flow"]').click();await page.setViewportSize({width:1366,height:768});}
for(const scenario of ['running','error','unavailable']){await page.selectOption('#scenario',scenario);await nav('overview');await shot('overview-'+scenario);}
await page.selectOption('#scenario','scheduler-error');await nav('automation');await page.locator('[data-action="edit-auto-schedule"]').click();await page.selectOption('[name=schedule]','12h');await page.locator('#flow-next').click();await page.locator('[data-action="edit-auto-schedule"]').waitFor();assert.match(await page.locator('.notice').textContent(),/Settings saved/);await shot('saved-scheduler-failed');
await page.selectOption('#scenario','configured');await nav('automation');await page.locator('[data-action="edit-auto-schedule"]').click();await page.selectOption('[name=schedule]','12h');await page.locator('#flow-next').click();await page.selectOption('#scenario','empty');await page.waitForTimeout(600);assert.equal(await page.locator('[data-action="start-auto"]').count(),1);
assert.deepEqual(errors,[]);assert(requests.every(url=>!url.endsWith('.php')));console.log('PASS: isolated preview, task navigation, compact steps, quick editing, connection return, drafts, save errors, captured selection, reviews, logs, migration, themes and narrow layouts');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
