const {chromium}=require('/opt/zfsas-tests/node_modules/playwright-core');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');
const plugin=path.resolve(__dirname,'../../source/usr/local/emhttp/plugins/zfs.snapsync');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:900}});let submitted=0,fail=true,deleted=false,inspected=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const session={token:'a'.repeat(32),dataset:'tank/data',auto:true,jobs:[{source:'tank/data',destination:'backup/data',transport:'local'}],targets:[{dataset:'tank/data',role:'source',transport:'local'},{dataset:'backup/data',role:'destination',transport:'local'}],conflicts:[],busy:[]};
 await page.route('http://retire.test/**',async route=>{const url=new URL(route.request().url());let payload={ok:true};
 if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:execFileSync('php',['-r','$_GET["section"]="snapshots";require $argv[1];',plugin+'/php/workspace.php'],{encoding:'utf8'})});
 if(url.pathname.endsWith('.png'))return route.fulfill({contentType:'image/png',body:fs.readFileSync(plugin+url.pathname.replace('/plugins/zfs.snapsync',''))});
 if(/\.(css|js)$/.test(url.pathname))return route.fulfill({contentType:url.pathname.endsWith('.js')?'application/javascript':'text/css',body:fs.readFileSync(plugin+'/'+(url.pathname.endsWith('.js')?'js/':'css/')+path.basename(url.pathname),'utf8')});
 if(url.pathname.endsWith('dataset-inventory.php'))payload.datasets=[{dataset:'tank/data',pool:'tank',snapshotCount:0}];
 else if(url.pathname.endsWith('snapshot-manager-dataset.php'))Object.assign(payload,{dataset:'tank/data',snapshots:[],matching:0,total:0,page:1,pages:1});
 else if(url.pathname.endsWith('dataset-retirement.php')){const body=route.request().method()==='GET'?url.searchParams:new URLSearchParams(route.request().postData());const action=body.get('action');payload={ok:true,...session};
 if(action==='inspect'){inspected++;if(inspected>1)assert.deepEqual(JSON.parse(body.get('destinations')),[{dataset:'backup/data',transport:'local'}]);}
 if(action==='stop'){if(fail){fail=false;payload={ok:false,error:'Settings changed. Inspect retirement again.'};}else Object.assign(payload,{saved:true,schedulerApplied:true,message:'Automation stopped.'});}
 if(action==='status')Object.assign(payload,{run:{state:'complete'},...(deleted?{deleteRun:'run-done'}:{}),total:10000,eligible:9999,selected:9998,tasks:[],rows:[{key:'1'.repeat(64),snapshot:'tank/data@auto-one',role:'source',transport:'local',selected:true,reason:''},{key:'2'.repeat(64),snapshot:'backup/data@send-held',role:'destination',transport:'local',selected:false,reason:'Snapshot is held.'}]});
 if(action==='submit'){submitted++;assert.equal(body.get('confirm'),'1');assert.deepEqual(JSON.parse(body.get('excluded')),['1'.repeat(64)]);deleted=true;Object.assign(payload,{deleteRun:'run-done'});}
 }
 return route.fulfill({contentType:'text/plain',body:'ZFSAS_JSON_BEGIN'+JSON.stringify(payload)+'ZFSAS_JSON_END'});});
 await page.goto('http://retire.test/');await page.selectOption('#dataset','tank/data');const trigger=page.locator('#retirement-open');await trigger.waitFor({state:'visible',timeout:5000}).catch(async error=>{throw new Error(error.message+' '+JSON.stringify(errors)+' '+await trigger.evaluate(el=>el.parentElement.outerHTML));});await trigger.focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Stop automation',exact:true}).click();await page.getByText('Settings changed. Inspect retirement again.',{exact:true}).waitFor();assert(await page.locator('#dataset-retirement').evaluate(el=>el.open),'Save failure closed dialog');
 await page.getByRole('button',{name:'Stop automation',exact:true}).click();await page.getByText('9998 snapshots selected across all review pages.',{exact:true}).waitFor();assert(await page.locator('.retirement-snapshot input').nth(1).isDisabled());if(process.env.ZFSAS_DOC_CAPTURE){fs.mkdirSync('/tmp/zfsas-ui-screenshots',{recursive:true});for(const theme of ['light','dark']){await page.evaluate(theme=>document.body.style.backgroundColor=theme==='dark'?'rgb(25,25,25)':'rgb(255,255,255)',theme);await page.screenshot({path:'/tmp/zfsas-ui-screenshots/retirement-review-'+theme+'-'+width+'.png'});}}
 await page.locator('.retirement-snapshot input').first().uncheck();await page.getByRole('button',{name:'Delete 9997 snapshots',exact:true}).click();await page.getByText('Automation remains stopped. Cleanup: complete.',{exact:true}).waitFor();assert.equal(submitted,1);await page.getByRole('button',{name:'Review remaining snapshots',exact:true}).click();await page.getByRole('button',{name:'Stop automation',exact:true}).waitFor();await page.keyboard.press('Escape');assert(await trigger.evaluate(el=>el===document.activeElement),'Focus not restored');assert.deepEqual(errors,[]);await page.close();
}console.log('PASS: retirement workflow desktop/mobile, saved-error preservation, captured global selection, held exclusions, single submit and keyboard focus');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
