<?php $isOverview = $uiSection === 'overview'; ?>
<?php if ($isOverview): ?>
<div class="ui-metrics" aria-label="Runtime summary"><div class="ui-metric"><span>Active work in recent records</span><strong id="summary-active">—</strong><small>Queued, running, or waiting</small></div><div class="ui-metric"><span>Needs attention</span><strong id="summary-attention">—</strong><small>Reported failures and recovery</small></div><div class="ui-metric"><span>Paused schedules</span><strong id="summary-paused">—</strong><small>Resume explicitly when ready</small></div></div>
<div id="summary-availability" aria-live="polite"></div>
<div class="ui-two-column"><section class="ui-card"><div class="ui-card-heading"><h2>Upcoming schedules</h2><a href="<?= zfsas_ui_url('snapshots','automation') ?>">Manage →</a></div><div id="upcoming-schedules"><p class="muted">Loading schedule information…</p></div><p class="ui-footnote">Host timezone: <span data-host-zone>—</span>. Work starts when its dependencies and resources are ready.</p></section><section class="ui-card"><div class="ui-card-heading"><h2>Needs attention</h2><a href="<?= zfsas_ui_url('activity') ?>">View activity →</a></div><div id="attention-list"><p class="muted">Checking recent records…</p></div></section></div>
<?php else: ?>
<div class="ui-notice">Recent history is kept in RAM for this boot and may be incomplete. After reboot, manual transfers require explicit Retry and snapshot batches require fresh review.</div>
<div id="summary-availability" aria-live="polite"></div>
<div class="toolbar"><label>Operation<select id="activity-type"><option value="">All types</option><option value="auto">Automatic snapshots</option><option value="replication">Replication</option><option value="batch">Snapshot batches</option><option value="migration">Migration</option></select></label><label>State<select id="activity-state"><option value="">All states</option><option value="active">Active</option><option value="failed">Needs attention</option><option value="complete">Completed</option><option value="canceled">Canceled</option></select></label><button type="button" id="activity-refresh">Refresh</button><span class="muted">Host timezone: <span data-host-zone>—</span></span></div>
<?php endif; ?>
<section class="ui-card"><div class="ui-card-heading"><h2><?= $isOverview ? 'Current & recent work' : 'Operations' ?></h2><span id="activity-updated" class="muted">Connecting…</span></div><div class="table-wrap"><table class="ui-operations-table"><thead><tr><th>Operation</th><th>Dataset / destination</th><th>Status</th><th>Requested</th><th></th></tr></thead><tbody id="operation-rows"><tr><td colspan="5" class="ui-empty">Loading runtime records…</td></tr></tbody></table></div><p class="ui-footnote">Up to 120 recent operation records. Internal worker attempts are omitted; child transfers retain their recorded run relationship.</p></section>
<?php if (!$isOverview): ?><section class="ui-card"><details id="activity-logs"><summary>Logs</summary><div class="toolbar"><label>Log source<select id="activity-log-type"><option value="auto">Latest Auto Snapshot run</option><option value="debug">Auto Snapshot debug</option><option value="replication">Replication</option><option value="migration">Migration</option><option value="batch">Snapshot batches</option><option value="coordinator">Coordinator</option></select></label><button type="button" id="activity-log-refresh">Refresh log</button><a class="btn" href="/plugins/zfs.snapsync/php/log-tail.php?download=1">Download Auto Snapshot logs</a></div><p class="ui-footnote">Last 200 lines. Shared logs may include other operations.</p><pre id="activity-log-output">Choose a log source.</pre></details></section><?php endif; ?>
<dialog id="operation-detail" aria-labelledby="operation-title"><div class="ui-dialog-header"><h2 id="operation-title">Operation details</h2><button type="button" data-close-dialog aria-label="Close operation details">Close</button></div><div id="operation-body"></div><div id="operation-actions" class="toolbar"></div><p id="operation-action-message" role="status"></p></dialog>
<script src="/plugins/zfs.snapsync/js/operations.js"></script>
